version: '3'
services:
  task-app-server:
    build: ./task-app
    container_name: task-app-server
    ports:
      - 8080:8080
      - 8081:8081
  
  task-app-ui:
    build: ./task-app-ui
    container_name: task-app-ui
    ports:
      - 80:80
    links:
      - task-app-server
