name: Cypress E2E CI
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup JdK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: ./task-app/
        run: mvn --batch-mode --update-snapshots clean package
      - name: Run JAR
        working-directory: ./task-app/
        run: java -jar target/taskapp-1.0-SNAPSHOT.jar server ./config.yml &

      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          working-directory: ./task-app-ui
      - name: NPM install
        run: npm i
        working-directory: ./task-app-ui
      - name: NPM Test
        working-directory: ./task-app-ui
        run: npm test

      - name: Cypress Run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: false
          browser: chrome
          working-directory: ./task-app-ui